{
 "title": "MLOps System Dashboard",
 "tags": [ "mlops" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество данных (Свечи)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "allValues" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n    ticker,\r\n    COUNT(*) as \" \"\r\nFROM market_candles\r\nGROUP BY ticker"
    }
   ]
  },
  {
   "title": "Популярность акций (Запросы)",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  ticker,\r\n  count(*) as requests_count\r\nFROM prediction_logs\r\nGROUP BY ticker"
    }
   ]
  },
  {
   "title": "Общая статистика",
   "type": "stat",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  count(*) AS \"Число запросов\"\r\nFROM prediction_logs;"
    },
    {
     "rawSql": "SELECT\r\n  avg(processing_time_ms) AS \"Среднее время ответа, мс\"\r\nFROM prediction_logs;"
    }
   ]
  },
  {
   "title": "Нагрузка (RPS)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(requested_at, '1m') as \"time\",\r\n  count(*) as \"Запросов в минуту\"\r\nFROM prediction_logs\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Latency (Скорость ответа)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(requested_at, '1m') as \"time\",\r\n  avg(processing_time_ms) as \"Средняя задержка (мс)\"\r\nFROM prediction_logs\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Тренд прогнозов (Рост vs Падение)",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  $__timeGroup(requested_at, '1h') as \"time\",\r\n  count(*) FILTER (WHERE predicted_end_price > predicted_start_price) as \"Рост\",\r\n  count(*) FILTER (WHERE predicted_end_price < predicted_start_price) as \"Падение\"\r\nFROM prediction_logs\r\nGROUP BY 1\r\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Лог последних запросов",
   "type": "table",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 26 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  requested_at as \"Time\",\r\n  ticker as \"Ticker\",\r\n  horizon_hours as \"Horizon (h)\",\r\n  predicted_start_price as \"Start Price\",\r\n  predicted_end_price as \"End Price\",\r\n  processing_time_ms as \"Latency (ms)\"\r\nFROM prediction_logs\r\nORDER BY requested_at DESC\r\nLIMIT 100"
    }
   ]
  },
  {
   "title": "Последняя известная цена",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT DISTINCT ON (ticker)\r\n    ticker,\r\n    close AS last_close\r\nFROM market_candles\r\nORDER BY ticker, ts DESC;"
    }
   ]
  }
 ]
}